# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  dockerId: rajeshpatil74  # Replace with your Docker ID for Docker Hub or the admin user name for the Azure Container Registry
  imageName: newtestproj  # Replace with the name of the image you want to publish
  pswd: rajesh1234
  tagName: '$(Build.BuildNumber)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: |
        docker build -t $(dockerId)/$(imageName):$(tagName) .
        docker login https://a59d6472.ngrok.io   #-u $(dockerId) -p $(pswd)
        docker push $(dockerId)/$(imageName):$(tagName)
      env:
        pswdtest: $(dockerPassword)

